Feature/say yml path
MAAP-Project/algorithms-jupyter-extension pull request #12
Opened 2024-08-12 23:03 UTC by grallewellyn

<img width="501" alt="Screenshot 2024-08-12 at 3 56 48 PM" src="https://github.com/user-attachments/assets/af27440e-bf32-42d8-91aa-9125d9c39a82">

Can test with this image: 'mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/python:say-yml-path'

There is another ticket for putting the yml files into a folder

2024-08-12 23:51 UTC, grallewellyn commented
@marjo-luc Are you okay with algorithms extension handling where the yml file goes because it is the one creating the file? Before we said we want the API to return where the file was created, but I am not sure how the API would know unless we changed who created the file 
https://github.com/MAAP-Project/algorithms-jupyter-extension/blob/470547725bd33b72fd44cebef485418e8752cf74/src/utils/api.ts#L50

2024-08-14 21:54 UTC, marjo-luc requested changes
Minor change request, but looks good otherwise.

2024-08-14 21:54 UTC, marjo-luc commented on src/components/RegistrationForm.tsx
> +                        <br />
Adding an extra break to make the text more readable.

```suggestion
                        <br />
                        <br />
```

2024-08-14 23:02 UTC, marjo-luc approved these changes

2024-08-15 15:15 UTC, merged